language: python
python:
    - '2.7'
env:
    global:
        - secure: "o9AdBDz0C08hKdWDcv2Ks2rkGXB1HtAYWfnIPgNeG8mtr6iETz6WdpgENhKjFUhhPdgda/MTGJMKxoXIG0+2MpAiimF8Y8rV83vNAs+5aKH/amfFK89j0IcEYnDuQxZQfuBYmcMIBex7VUcqKjMzBNHg0vsX22j+CS2XSmAdN9g="
        - secure: "aI1GiJ3Hubc3uMq01WdnV3iaF6wtm8rBjUiam45J8Z99Xe2xB/lGPyJfYfpWFN4BhcD4UoC2oneIwRu87zNW2cN+nCZ9ltY5/vfRJSY8ML3ndDQSUxR3TZ/jW8VN3pqHhh0/V7bEonAMrX8z/6RT/XMcohwDmCGe+zWK1xX9eeg="
        - secure: "Knz7E+RQTynPaMeU9KzK+LKemaPsXg6ReDQIaL9wcJYQnu2/S4wEbHQSEQZaUnqBNcCyzsxT3uivTlIjbMZmnT6/CGzEuvAZi0CNckExTuvi5GrSnlDh6O86tE9/CxlKo2M9fPcB3Ib2kO6T7OgMN0g4zBKtGQLmwjqYL1gywtY="
install:
    - export PYTHONPATH=$PYTHONPATH:/Users/simonstanley/miniconda/bin/:$(pwd)
    - pip install pylint
    - pip install -r requirements.txt
    - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh
    - bash ~/miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda install -c scitools --yes iris python=2.7
    - git clone git://github.com/boto/boto.git
    - cd boto
    - python setup.py install
    - cd ..
script:
    - python tests/unit/UTcoverage.py
    - python tests/unit/UTrequester.py
    - python tests/unit/UTxml_reader.py
    - python tests/integration/requester_test.py
    - pylint -E --disable=E1101 BDS
